export { default as Titulo2 } from './Titulo2'
export { default as Titulo3 } from './Titulo3'
export { default as Titulo4 } from './Titulo4'
export { default as Titulo5 } from './Titulo5'
export { default as Titulo6 } from './Titulo6'